swagger: '2.0'
info:
  title: wise-api
  description: API endpoints for Wise.
  version: 1.0.0
schemes:
    - https
produces:
  - application/json
paths:
  /conversations:
    get:
      description: Get all conversations for user.
      operationId: getConversations
      x-google-backend:
        address: https://us-south1-wise-api.cloudfunctions.net/conversations
      parameters:
        - name: user
          in: query
          required: true
          type: string
      responses:
        200:
          description: Conversations list
          schema:
            type: array
            properties:
              conversations:
                type: array
                items:
                  $ref: '#/definitions/Conversation'
        400:
          description: The userId is invalid or missing.

definitions:
  Conversation:
    type: object
    properties:
      id:
        type: integer
      text:
        type: array
        items:
          type: string
